from .service_definition import ServiceDefinition

AWS_SERVICES: list[ServiceDefinition] = [
    # ── Identity & Access ─────────────────────────────────────────────────
    ServiceDefinition(
        key="iam",
        provider="aws",
        display_name="IAM",
        module_path="cartography.intel.aws.iam",
        function_name="sync",
        requires_region=False,
        description="Users, roles, groups, policies and their permission relationships.",
    ),
    ServiceDefinition(
        key="iaminstanceprofiles",
        provider="aws",
        display_name="IAM Instance Profiles",
        module_path="cartography.intel.aws.iam_instance_profiles",
        function_name="sync_iam_instance_profiles",
        requires_region=False,
        depends_on=["iam"],
        description="EC2 instance profiles and their attached IAM roles.",
    ),
    # ── Networking (must come before compute) ────────────────────────────
    ServiceDefinition(
        key="ec2:vpc",
        provider="aws",
        display_name="EC2 VPCs",
        module_path="cartography.intel.aws.ec2.vpc",
        function_name="sync_vpc",
        description="Virtual Private Clouds — network isolation boundaries.",
    ),
    ServiceDefinition(
        key="ec2:subnet",
        provider="aws",
        display_name="EC2 Subnets",
        module_path="cartography.intel.aws.ec2.subnets",
        function_name="sync_subnets",
        depends_on=["ec2:vpc"],
        description="Subnets within VPCs and their availability zone placement.",
    ),
    ServiceDefinition(
        key="ec2:security_group",
        provider="aws",
        display_name="EC2 Security Groups",
        module_path="cartography.intel.aws.ec2.security_groups",
        function_name="sync_ec2_security_groupinfo",
        depends_on=["ec2:vpc"],
        description="Security groups — inbound/outbound traffic rules.",
    ),
    ServiceDefinition(
        key="ec2:vpc_endpoint",
        provider="aws",
        display_name="VPC Endpoints",
        module_path="cartography.intel.aws.ec2.vpc_endpoint",
        function_name="sync_vpc_endpoints",
        depends_on=["ec2:vpc"],
        description="VPC endpoints for private AWS service access.",
    ),
    ServiceDefinition(
        key="ec2:route_table",
        provider="aws",
        display_name="Route Tables",
        module_path="cartography.intel.aws.ec2.route_tables",
        function_name="sync_route_tables",
        depends_on=["ec2:vpc", "ec2:subnet", "ec2:vpc_endpoint"],
        description="VPC route tables and their subnet associations.",
    ),
    ServiceDefinition(
        key="ec2:internet_gateway",
        provider="aws",
        display_name="Internet Gateways",
        module_path="cartography.intel.aws.ec2.internet_gateways",
        function_name="sync_internet_gateways",
        depends_on=["ec2:vpc"],
        description="Internet gateways attached to VPCs.",
    ),
    ServiceDefinition(
        key="ec2:network_acls",
        provider="aws",
        display_name="Network ACLs",
        module_path="cartography.intel.aws.ec2.network_acls",
        function_name="sync_network_acls",
        depends_on=["ec2:vpc"],
        description="Stateless subnet-level traffic rules.",
    ),
    ServiceDefinition(
        key="ec2:vpc_peering",
        provider="aws",
        display_name="VPC Peering",
        module_path="cartography.intel.aws.ec2.vpc_peerings",
        function_name="sync_vpc_peerings",
        depends_on=["ec2:vpc"],
        description="VPC peering connections between accounts or regions.",
    ),
    ServiceDefinition(
        key="ec2:tgw",
        provider="aws",
        display_name="Transit Gateways",
        module_path="cartography.intel.aws.ec2.tgw",
        function_name="sync_transit_gateways",
        depends_on=["ec2:vpc"],
        description="Transit gateways and their VPC attachments.",
    ),
    # ── Compute ───────────────────────────────────────────────────────────
    ServiceDefinition(
        key="ec2:launch_templates",
        provider="aws",
        display_name="EC2 Launch Templates",
        module_path="cartography.intel.aws.ec2.launch_templates",
        function_name="sync_ec2_launch_templates",
        description="Launch templates for EC2 instance configuration.",
    ),
    ServiceDefinition(
        key="ec2:autoscalinggroup",
        provider="aws",
        display_name="EC2 Auto Scaling Groups",
        module_path="cartography.intel.aws.ec2.auto_scaling_groups",
        function_name="sync_ec2_auto_scaling_groups",
        depends_on=["ec2:launch_templates"],
        description="Auto scaling groups and their launch configurations.",
    ),
    ServiceDefinition(
        key="ec2:instance",
        provider="aws",
        display_name="EC2 Instances",
        module_path="cartography.intel.aws.ec2.instances",
        function_name="sync_ec2_instances",
        depends_on=["ec2:vpc", "ec2:subnet", "ec2:security_group"],
        description="EC2 compute instances, state, type, and network placement.",
    ),
    ServiceDefinition(
        key="ec2:images",
        provider="aws",
        display_name="EC2 AMIs",
        module_path="cartography.intel.aws.ec2.images",
        function_name="sync_ec2_images",
        depends_on=["ec2:instance"],
        description="AMIs used by running EC2 instances.",
    ),
    ServiceDefinition(
        key="ec2:keypair",
        provider="aws",
        display_name="EC2 Key Pairs",
        module_path="cartography.intel.aws.ec2.key_pairs",
        function_name="sync_ec2_key_pairs",
        depends_on=["ec2:instance"],
        description="EC2 SSH key pairs.",
    ),
    ServiceDefinition(
        key="ec2:network_interface",
        provider="aws",
        display_name="EC2 Network Interfaces",
        module_path="cartography.intel.aws.ec2.network_interfaces",
        function_name="sync_network_interfaces",
        depends_on=["ec2:instance", "ec2:security_group"],
        description="ENIs — the bridge between EC2 instances and security groups.",
    ),
    ServiceDefinition(
        key="ec2:volumes",
        provider="aws",
        display_name="EBS Volumes",
        module_path="cartography.intel.aws.ec2.volumes",
        function_name="sync_ebs_volumes",
        depends_on=["ec2:instance"],
        description="EBS block storage volumes and instance attachments.",
    ),
    ServiceDefinition(
        key="ec2:snapshots",
        provider="aws",
        display_name="EBS Snapshots",
        module_path="cartography.intel.aws.ec2.snapshots",
        function_name="sync_ebs_snapshots",
        depends_on=["ec2:volumes"],
        description="EBS volume snapshots.",
    ),
    ServiceDefinition(
        key="ec2:reserved_instances",
        provider="aws",
        display_name="EC2 Reserved Instances",
        module_path="cartography.intel.aws.ec2.reserved_instances",
        function_name="sync_ec2_reserved_instances",
        description="Reserved instance commitments.",
    ),
    ServiceDefinition(
        key="elastic_ip_addresses",
        provider="aws",
        display_name="Elastic IPs",
        module_path="cartography.intel.aws.ec2.elastic_ip_addresses",
        function_name="sync_elastic_ip_addresses",
        depends_on=["ec2:instance", "ec2:network_interface"],
        description="Elastic IP addresses and their EC2/ENI associations.",
    ),
    ServiceDefinition(
        key="ec2:load_balancer",
        provider="aws",
        display_name="Classic Load Balancers",
        module_path="cartography.intel.aws.ec2.load_balancers",
        function_name="sync_load_balancers",
        depends_on=["ec2:instance", "ec2:subnet", "ec2:security_group"],
        description="Classic (v1) load balancers.",
    ),
    ServiceDefinition(
        key="ec2:load_balancer_v2",
        provider="aws",
        display_name="ALB/NLB",
        module_path="cartography.intel.aws.ec2.load_balancer_v2s",
        function_name="sync_load_balancer_v2s",
        depends_on=["ec2:instance", "ec2:security_group", "ec2:subnet"],
        description="Application and Network Load Balancers and target groups.",
    ),
    ServiceDefinition(
        key="ec2:load_balancer_v2:expose",
        provider="aws",
        display_name="ALB/NLB IP Exposure",
        module_path="cartography.intel.aws.ec2.load_balancer_v2s",
        function_name="sync_load_balancer_v2_expose",
        depends_on=["ec2:load_balancer_v2", "ec2:network_interface"],
        description="IP target exposure links for ALB/NLB.",
    ),
    # ── Containers ────────────────────────────────────────────────────────
    ServiceDefinition(
        key="ecr",
        provider="aws",
        display_name="ECR",
        module_path="cartography.intel.aws.ecr",
        function_name="sync",
        description="ECR container registries and image repositories.",
    ),
    ServiceDefinition(
        key="ecr:image_layers",
        provider="aws",
        display_name="ECR Image Layers",
        module_path="cartography.intel.aws.ecr_image_layers",
        function_name="sync",
        depends_on=["ecr"],
        description="ECR image layer metadata.",
    ),
    ServiceDefinition(
        key="ecs",
        provider="aws",
        display_name="ECS",
        module_path="cartography.intel.aws.ecs",
        function_name="sync",
        depends_on=["iam", "ec2:instance", "ec2:security_group"],
        description="ECS clusters, services, tasks and container definitions.",
    ),
    ServiceDefinition(
        key="eks",
        provider="aws",
        display_name="EKS",
        module_path="cartography.intel.aws.eks",
        function_name="sync",
        depends_on=["iam", "ec2:security_group", "ec2:subnet"],
        description="EKS Kubernetes clusters and node groups.",
    ),
    # ── Serverless ────────────────────────────────────────────────────────
    ServiceDefinition(
        key="lambda_function",
        provider="aws",
        display_name="Lambda",
        module_path="cartography.intel.aws.lambda_function",
        function_name="sync",
        depends_on=["iam"],
        description="Lambda functions, runtimes, VPC config and IAM roles.",
    ),
    ServiceDefinition(
        key="apigateway",
        provider="aws",
        display_name="API Gateway v1",
        module_path="cartography.intel.aws.apigateway",
        function_name="sync",
        depends_on=["lambda_function"],
        description="REST APIs, stages, resources and Lambda integrations.",
    ),
    ServiceDefinition(
        key="apigatewayv2",
        provider="aws",
        display_name="API Gateway v2",
        module_path="cartography.intel.aws.apigatewayv2",
        function_name="sync",
        depends_on=["lambda_function"],
        description="HTTP and WebSocket APIs.",
    ),
    # ── Storage ───────────────────────────────────────────────────────────
    ServiceDefinition(
        key="s3",
        provider="aws",
        display_name="S3",
        module_path="cartography.intel.aws.s3",
        function_name="sync",
        requires_region=False,
        description="S3 buckets, policies, ACLs and encryption settings.",
    ),
    ServiceDefinition(
        key="s3accountpublicaccessblock",
        provider="aws",
        display_name="S3 Account Public Access Block",
        module_path="cartography.intel.aws.s3accountpublicaccessblock",
        function_name="sync",
        requires_region=False,
        depends_on=["s3"],
        description="Account-level S3 public access block settings.",
    ),
    ServiceDefinition(
        key="efs",
        provider="aws",
        display_name="EFS",
        module_path="cartography.intel.aws.efs",
        function_name="sync",
        depends_on=["ec2:security_group", "ec2:subnet"],
        description="EFS file systems and mount targets.",
    ),
    # ── Databases ─────────────────────────────────────────────────────────
    ServiceDefinition(
        key="kms",
        provider="aws",
        display_name="KMS",
        module_path="cartography.intel.aws.kms",
        function_name="sync",
        requires_region=False,
        description="KMS encryption keys and their aliases.",
    ),
    ServiceDefinition(
        key="dynamodb",
        provider="aws",
        display_name="DynamoDB",
        module_path="cartography.intel.aws.dynamodb",
        function_name="sync",
        depends_on=["kms"],
        description="DynamoDB tables, indices and stream configurations.",
    ),
    ServiceDefinition(
        key="rds",
        provider="aws",
        display_name="RDS",
        module_path="cartography.intel.aws.rds",
        function_name="sync",
        depends_on=["ec2:security_group", "ec2:subnet"],
        description="RDS database instances, clusters and subnet groups.",
    ),
    ServiceDefinition(
        key="redshift",
        provider="aws",
        display_name="Redshift",
        module_path="cartography.intel.aws.redshift",
        function_name="sync",
        depends_on=["ec2:security_group", "ec2:subnet"],
        description="Redshift clusters and their VPC configuration.",
    ),
    ServiceDefinition(
        key="elasticache",
        provider="aws",
        display_name="ElastiCache",
        module_path="cartography.intel.aws.elasticache",
        function_name="sync",
        depends_on=["ec2:security_group", "ec2:subnet"],
        description="ElastiCache Redis and Memcached clusters.",
    ),
    ServiceDefinition(
        key="elasticsearch",
        provider="aws",
        display_name="Elasticsearch",
        module_path="cartography.intel.aws.elasticsearch",
        function_name="sync",
        depends_on=["ec2:security_group"],
        description="Elasticsearch/OpenSearch domains.",
    ),
    # ── Messaging ─────────────────────────────────────────────────────────
    ServiceDefinition(
        key="sqs",
        provider="aws",
        display_name="SQS",
        module_path="cartography.intel.aws.sqs",
        function_name="sync",
        description="SQS queues and their access policies.",
    ),
    ServiceDefinition(
        key="sns",
        provider="aws",
        display_name="SNS",
        module_path="cartography.intel.aws.sns",
        function_name="sync",
        description="SNS topics and their subscriptions.",
    ),
    ServiceDefinition(
        key="eventbridge",
        provider="aws",
        display_name="EventBridge",
        module_path="cartography.intel.aws.eventbridge",
        function_name="sync",
        description="EventBridge event buses and rules.",
    ),
    # ── Security & Compliance ─────────────────────────────────────────────
    ServiceDefinition(
        key="secretsmanager",
        provider="aws",
        display_name="Secrets Manager",
        module_path="cartography.intel.aws.secretsmanager",
        function_name="sync",
        description="Secrets and their rotation configuration.",
    ),
    ServiceDefinition(
        key="cloudtrail",
        provider="aws",
        display_name="CloudTrail",
        module_path="cartography.intel.aws.cloudtrail",
        function_name="sync",
        requires_region=False,
        description="CloudTrail trails and their S3/CloudWatch destinations.",
    ),
    ServiceDefinition(
        key="cloudtrail_management_events",
        provider="aws",
        display_name="CloudTrail Management Events",
        module_path="cartography.intel.aws.cloudtrail_management_events",
        function_name="sync",
        depends_on=["cloudtrail"],
        description="CloudTrail management event history.",
    ),
    ServiceDefinition(
        key="securityhub",
        provider="aws",
        display_name="Security Hub",
        module_path="cartography.intel.aws.securityhub",
        function_name="sync",
        description="Security Hub findings and standards.",
    ),
    ServiceDefinition(
        key="guardduty",
        provider="aws",
        display_name="GuardDuty",
        module_path="cartography.intel.aws.guardduty",
        function_name="sync",
        description="GuardDuty detectors and threat findings.",
    ),
    ServiceDefinition(
        key="inspector",
        provider="aws",
        display_name="Inspector",
        module_path="cartography.intel.aws.inspector",
        function_name="sync",
        description="Inspector vulnerability findings for EC2 and Lambda.",
    ),
    ServiceDefinition(
        key="config",
        provider="aws",
        display_name="AWS Config",
        module_path="cartography.intel.aws.config",
        function_name="sync",
        description="AWS Config recorders and compliance rules.",
    ),
    ServiceDefinition(
        key="acm:certificate",
        provider="aws",
        display_name="ACM Certificates",
        module_path="cartography.intel.aws.acm",
        function_name="sync",
        description="ACM TLS certificates and their domain associations.",
    ),
    ServiceDefinition(
        key="ssm",
        provider="aws",
        display_name="SSM",
        module_path="cartography.intel.aws.ssm",
        function_name="sync",
        depends_on=["ec2:instance"],
        description="SSM managed instances and patch compliance.",
    ),
    # ── Observability ─────────────────────────────────────────────────────
    ServiceDefinition(
        key="cloudwatch",
        provider="aws",
        display_name="CloudWatch",
        module_path="cartography.intel.aws.cloudwatch",
        function_name="sync",
        description="CloudWatch log groups and alarms.",
    ),
    # ── DNS & CDN ─────────────────────────────────────────────────────────
    ServiceDefinition(
        key="route53",
        provider="aws",
        display_name="Route53",
        module_path="cartography.intel.aws.route53",
        function_name="sync",
        requires_region=False,
        description="Hosted zones and DNS record sets.",
    ),
    ServiceDefinition(
        key="cloudfront",
        provider="aws",
        display_name="CloudFront",
        module_path="cartography.intel.aws.cloudfront",
        function_name="sync",
        requires_region=False,
        description="CloudFront distributions and their origins.",
    ),
    # ── ML / Data ─────────────────────────────────────────────────────────
    ServiceDefinition(
        key="sagemaker",
        provider="aws",
        display_name="SageMaker",
        module_path="cartography.intel.aws.sagemaker",
        function_name="sync",
        depends_on=["iam"],
        description="SageMaker notebooks, training jobs and endpoints.",
    ),
    ServiceDefinition(
        key="bedrock",
        provider="aws",
        display_name="Bedrock",
        module_path="cartography.intel.aws.bedrock",
        function_name="sync",
        description="Bedrock foundation model access and custom models.",
    ),
    ServiceDefinition(
        key="glue",
        provider="aws",
        display_name="Glue",
        module_path="cartography.intel.aws.glue",
        function_name="sync",
        description="Glue data catalog, crawlers and ETL jobs.",
    ),
    ServiceDefinition(
        key="emr",
        provider="aws",
        display_name="EMR",
        module_path="cartography.intel.aws.emr",
        function_name="sync",
        depends_on=["ec2:security_group"],
        description="EMR clusters and their EC2 configurations.",
    ),
    # ── Developer Tools ───────────────────────────────────────────────────
    ServiceDefinition(
        key="codebuild",
        provider="aws",
        display_name="CodeBuild",
        module_path="cartography.intel.aws.codebuild",
        function_name="sync",
        depends_on=["iam"],
        description="CodeBuild projects and their IAM roles.",
    ),
    # ── Identity (SSO) ────────────────────────────────────────────────────
    ServiceDefinition(
        key="identitycenter",
        provider="aws",
        display_name="IAM Identity Center",
        module_path="cartography.intel.aws.identitycenter",
        function_name="sync_identity_center_instances",
        requires_region=False,
        depends_on=["iam"],
        description="IAM Identity Center instances, permission sets and assignments.",
    ),
    # ── Auth ──────────────────────────────────────────────────────────────
    ServiceDefinition(
        key="cognito",
        provider="aws",
        display_name="Cognito",
        module_path="cartography.intel.aws.cognito",
        function_name="sync",
        description="Cognito user pools and identity pools.",
    ),
    # ── Cross-service relationships ───────────────────────────────────────
    ServiceDefinition(
        key="permission_relationships",
        provider="aws",
        display_name="Permission Relationships",
        module_path="cartography.intel.aws.permission_relationships",
        function_name="sync",
        depends_on=["iam", "s3", "lambda_function"],
        description="Cross-service IAM permission edges (who can access what).",
    ),
    ServiceDefinition(
        key="resourcegroupstaggingapi",
        provider="aws",
        display_name="Resource Groups Tagging",
        module_path="cartography.intel.aws.resourcegroupstaggingapi",
        function_name="sync",
        description="Tag-based resource groupings across all services.",
    ),
]
