from .service_definition import ServiceDefinition

AZURE_SERVICES: list[ServiceDefinition] = [
    # ── Foundation (no deps — must come first) ────────────────────────────
    ServiceDefinition(
        key="resource_groups",
        provider="azure",
        display_name="Resource Groups",
        module_path="cartography.intel.azure.resource_groups",
        function_name="sync",
        requires_region=False,
        description="Azure resource groups — the container for all other resources.",
    ),
    # ── Networking (depends on resource_groups, needed by compute) ────────
    ServiceDefinition(
        key="network",
        provider="azure",
        display_name="Network",
        module_path="cartography.intel.azure.network",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Virtual networks, subnets and network security groups.",
    ),
    # ── Storage (needed by app_service, functions, data_lake, synapse) ────
    ServiceDefinition(
        key="storage",
        provider="azure",
        display_name="Storage",
        module_path="cartography.intel.azure.storage",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure storage accounts, blob containers and queues.",
    ),
    # ── Compute ───────────────────────────────────────────────────────────
    ServiceDefinition(
        key="compute",
        provider="azure",
        display_name="Compute",
        module_path="cartography.intel.azure.compute",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure virtual machines and attached disks.",
    ),
    # ── Containers ────────────────────────────────────────────────────────
    ServiceDefinition(
        key="aks",
        provider="azure",
        display_name="AKS",
        module_path="cartography.intel.azure.aks",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure Kubernetes Service clusters and node pools.",
    ),
    ServiceDefinition(
        key="container_instances",
        provider="azure",
        display_name="Container Instances",
        module_path="cartography.intel.azure.container_instances",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure Container Instances and their container groups.",
    ),
    # ── Serverless & App Platform ─────────────────────────────────────────
    ServiceDefinition(
        key="app_service",
        provider="azure",
        display_name="App Service",
        module_path="cartography.intel.azure.app_service",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "storage"],
        description="Azure App Service web apps and app service plans.",
    ),
    ServiceDefinition(
        key="functions",
        provider="azure",
        display_name="Functions",
        module_path="cartography.intel.azure.functions",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "storage"],
        description="Azure Functions apps and their function definitions.",
    ),
    # ── Databases ─────────────────────────────────────────────────────────
    ServiceDefinition(
        key="sql",
        provider="azure",
        display_name="SQL",
        module_path="cartography.intel.azure.sql",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure SQL servers, databases and firewall rules.",
    ),
    ServiceDefinition(
        key="cosmosdb",
        provider="azure",
        display_name="CosmosDB",
        module_path="cartography.intel.azure.cosmosdb",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure Cosmos DB accounts and databases.",
    ),
    # ── Analytics & Data ──────────────────────────────────────────────────
    ServiceDefinition(
        key="data_lake",
        provider="azure",
        display_name="Data Lake",
        module_path="cartography.intel.azure.data_lake",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "storage"],
        description="Azure Data Lake Storage Gen2 accounts and filesystems.",
    ),
    ServiceDefinition(
        key="synapse",
        provider="azure",
        display_name="Synapse",
        module_path="cartography.intel.azure.synapse",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "storage"],
        description="Azure Synapse Analytics workspaces and SQL pools.",
    ),
    # ── Messaging & Events ────────────────────────────────────────────────
    ServiceDefinition(
        key="event_grid",
        provider="azure",
        display_name="Event Grid",
        module_path="cartography.intel.azure.event_grid",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure Event Grid topics and event subscriptions.",
    ),
    ServiceDefinition(
        key="logic_apps",
        provider="azure",
        display_name="Logic Apps",
        module_path="cartography.intel.azure.logic_apps",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure Logic Apps workflows and triggers.",
    ),
    # ── Security ──────────────────────────────────────────────────────────
    ServiceDefinition(
        key="key_vaults",
        provider="azure",
        display_name="Key Vaults",
        module_path="cartography.intel.azure.key_vaults",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure Key Vault instances, keys, secrets and certificates.",
    ),
    ServiceDefinition(
        key="firewall",
        provider="azure",
        display_name="Firewall",
        module_path="cartography.intel.azure.firewall",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure Firewall instances and firewall policies.",
    ),
    ServiceDefinition(
        key="security_center",
        provider="azure",
        display_name="Security Center",
        module_path="cartography.intel.azure.security_center",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure Security Center assessments and secure scores.",
    ),
    # ── Load Balancing ────────────────────────────────────────────────────
    ServiceDefinition(
        key="load_balancers",
        provider="azure",
        display_name="Load Balancers",
        module_path="cartography.intel.azure.load_balancers",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups", "network"],
        description="Azure Load Balancers, frontend IPs and backend pools.",
    ),
    # ── IAM & Access ─────────────────────────────────────────────────────
    ServiceDefinition(
        key="rbac",
        provider="azure",
        display_name="RBAC",
        module_path="cartography.intel.azure.rbac",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure role-based access control — role assignments and definitions.",
    ),
    # ── Observability ─────────────────────────────────────────────────────
    ServiceDefinition(
        key="monitor",
        provider="azure",
        display_name="Monitor",
        module_path="cartography.intel.azure.monitor",
        function_name="sync",
        requires_region=False,
        depends_on=["resource_groups"],
        description="Azure Monitor diagnostic settings and activity logs.",
    ),
]
